"""
Generated by Claude Opus 4.8 via web chat. Do not modify this file; it serves
as a reference implementation.

Toy "highest-scoring move" network for Scrabble.

Target:  f(board, rack) = max over legal placements of score(placement)
Design principle (from the discussion):
  * the MAX is structural, not learned -- the net densely predicts a best-score
    per (lane, anchor) and a pooling layer takes the max;
  * the LEXICON lives in the FFN width of a single shared "lane model" L;
  * L is run TWICE -- once on rows, once on cols (transpose-shared weights).
    The row-run scores horizontal words; the col-run scores the vertical words
    that act as cross-words for horizontal plays. Cross-checking and
    main-word-scoring are the SAME operation, applied on two axes.
  * cross-word legality and main-word score are computed independently from the
    board in both orientations, then CONJOINED at the placement-scoring head.
    (No circularity: nothing feeds the store its own prerequisite.)

Index conventions
-----------------
Board square contents `board`: LongTensor (B, S, S), values in [0, 26]
    0      = empty
    1..26  = letters A..Z   (a played blank ALSO uses its designated letter id
             here, so word formation sees the letter; scoring zeroes it via
             `blank_mask`)
`blank_mask`: FloatTensor (B, S, S), 1.0 where the on-board tile is a blank.
`wmult`, `lmult`: LongTensor (B, S, S) in {0,1,2} encoding word/letter
    multiplier ∈ {x1,x2,x3} for that square (premium layout).
`rack`: FloatTensor (B, 27) exact counts; index 0 = blanks, 1..26 = A..Z.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

S = 15           # board side
N_TILE = 27      # 0 empty + 26 letters
N_LET = 26


# ---------------------------------------------------------------------------
# Rack encoder: exact counts -> (FiLM params, rack tokens)
# ---------------------------------------------------------------------------
class RackEncoder(nn.Module):
    """Exact rack counts drive (a) FiLM modulation of the board features and
    (b) a few rack tokens that get prepended to every lane so the lane model
    can attend rack<->board. Counts must be EXACT ('can I play two R's' is a
    counting fact), so we feed the raw 27-vector, not a presence bitmask."""

    def __init__(self, C, n_tokens, hidden=256):
        super().__init__()
        self.C, self.n_tokens = C, n_tokens
        self.mlp = nn.Sequential(
            nn.Linear(27, hidden), nn.GELU(),
            nn.Linear(hidden, hidden), nn.GELU(),
        )
        self.to_film = nn.Linear(hidden, 2 * C)
        self.to_tokens = nn.Linear(hidden, n_tokens * C)

    def forward(self, rack):                       # rack: (B, 27)
        h = self.mlp(rack)
        gamma, beta = self.to_film(h).chunk(2, dim=-1)   # (B, C) each
        tokens = self.to_tokens(h).view(-1, self.n_tokens, self.C)  # (B, nt, C)
        return gamma, beta, tokens


# ---------------------------------------------------------------------------
# KataGo-style residual block with a global-pooling bias branch.
# Lets every cell know board-global facts (which lanes are open, is the board
# empty -> center only, etc.) without leaving convolution.
# ---------------------------------------------------------------------------
class GPResBlock(nn.Module):
    def __init__(self, C, Cg, groups=8):
        super().__init__()
        self.norm1 = nn.GroupNorm(groups, C)
        self.conv1 = nn.Conv2d(C, C, 3, padding=1)
        self.conv_g = nn.Conv2d(C, Cg, 3, padding=1)       # branch to pool
        self.fc_g = nn.Linear(2 * Cg, C)                   # mean+max -> chan bias
        self.norm2 = nn.GroupNorm(groups, C)
        self.conv2 = nn.Conv2d(C, C, 3, padding=1)

    def forward(self, x):                          # (B, C, S, S)
        h = self.conv1(F.gelu(self.norm1(x)))
        g = self.conv_g(h)                         # (B, Cg, S, S)
        gp = torch.cat([g.mean(dim=(2, 3)), g.amax(dim=(2, 3))], dim=1)  # (B,2Cg)
        h = h + self.fc_g(gp)[:, :, None, None]    # broadcast global bias
        h = self.conv2(F.gelu(self.norm2(h)))
        return x + h


# ---------------------------------------------------------------------------
# The shared lane model L -- THE lexical store.
# A small transformer over a length-(nt+S) sequence: nt prepended rack tokens
# + S board cells along one lane. Attention (not conv) because a word threads
# THROUGH existing tiles -> its letters are non-adjacent in the lane, and
# attention binds disjoint positions in one layer. The dictionary itself lives
# in the FFN width (key-value-memory view): width is the lexicon, attention is
# the index into it.
# ---------------------------------------------------------------------------
class LaneModel(nn.Module):
    def __init__(self, C, n_layers, n_heads, ffn_mult, max_len):
        super().__init__()
        layer = nn.TransformerEncoderLayer(
            d_model=C, nhead=n_heads, dim_feedforward=ffn_mult * C,
            activation="gelu", batch_first=True, norm_first=True,
        )
        self.enc = nn.TransformerEncoder(layer, n_layers)
        self.pos = nn.Parameter(torch.randn(1, max_len, C) * 0.02)

    def forward(self, x):                          # x: (M, L, C),  L = nt + S
        return self.enc(x + self.pos[:, : x.size(1)])


# ---------------------------------------------------------------------------
# Categorical (PMF) score head: B_k = 1[score == k] for k < n_bins-1, and the
# top bin is the catch-all 1[score >= n_bins-1]. The head emits n_bins logits;
# softmax gives the predicted PMF B_hat. Two losses (cf. discussion):
#   PDF-loss = cross-entropy   -sum_k B(k) log B_hat(k)   (sharpens the mode)
#   CDF-loss = discrete CRPS    sum_k (CDF_B(k) - CDF_Bhat(k))^2  (distance-aware)
# CRPS is the ordinal term: it penalizes probability mass by how FAR it sits
# from the true bin, which plain cross-entropy is blind to.
# ---------------------------------------------------------------------------
def pmf_expected_score(logits):
    """logits: (..., n_bins) -> E[score] (...,). Bin index == score; the top
    (catch-all) bin is valued at n_bins-1."""
    p = F.softmax(logits, dim=-1)
    k = torch.arange(p.size(-1), device=p.device, dtype=p.dtype)
    return (p * k).sum(dim=-1)


def score_pdf_loss(logits, target_bin, mask=None):
    """Cross-entropy. logits: (..., n_bins); target_bin: (...,) long in
    [0, n_bins-1] (clamp scores >= n_bins-1 to the top bin before calling).
    Optional mask: (...,) float/bool selecting valid anchors."""
    n = logits.size(-1)
    flat = logits.reshape(-1, n)
    tgt = target_bin.reshape(-1)
    ce = F.cross_entropy(flat, tgt, reduction="none")       # (-sum B log B_hat)
    if mask is not None:
        m = mask.reshape(-1).float()
        return (ce * m).sum() / m.sum().clamp_min(1.0)
    return ce.mean()


def score_cdf_loss(logits, target_bin, mask=None):
    """Discrete CRPS: sum_k (CDF_hat(k) - 1[k >= target])^2, averaged over
    anchors. CDF_B(k) is the step function rising at the true bin."""
    n = logits.size(-1)
    p = F.softmax(logits, dim=-1)
    cdf_hat = torch.cumsum(p, dim=-1).reshape(-1, n)        # (M, n_bins)
    ks = torch.arange(n, device=logits.device)
    cdf_tgt = (ks[None, :] >= target_bin.reshape(-1, 1)).float()
    per = ((cdf_hat - cdf_tgt) ** 2).sum(dim=-1)            # (M,)
    if mask is not None:
        m = mask.reshape(-1).float()
        return (per * m).sum() / m.sum().clamp_min(1.0)
    return per.mean()


# ---------------------------------------------------------------------------
# Full network.
# ---------------------------------------------------------------------------
class ScrabbleMaxScoreNet(nn.Module):
    def __init__(
        self,
        C=128,
        n_conv=8,
        gp_channels=32,
        lane_layers=4,
        lane_heads=4,
        ffn_mult=4,
        n_rack_tokens=8,
        n_score_bins=100,          # B_0..B_99; top bin = catch-all P(score>=99)
    ):
        super().__init__()
        self.C = C
        self.n_rack_tokens = n_rack_tokens

        # --- input embeddings ---
        self.letter_emb = nn.Embedding(N_TILE, 48)
        self.wmult_emb = nn.Embedding(3, 8)
        self.lmult_emb = nn.Embedding(3, 8)
        in_dim = 48 + 8 + 8 + 1                     # +1 for blank_mask plane
        self.stem = nn.Conv2d(in_dim, C, 1)

        # --- rack pathway ---
        self.rack_enc = RackEncoder(C, n_rack_tokens)

        # --- conv board encoder ---
        self.conv = nn.ModuleList([GPResBlock(C, gp_channels) for _ in range(n_conv)])

        # --- shared lane model (the lexical store) ---
        self.lane = LaneModel(C, lane_layers, lane_heads, ffn_mult,
                              max_len=n_rack_tokens + S)

        # --- heads (all shared across both orientations) ---
        # cross/main word legality, per square, per candidate letter:
        self.legal_head = nn.Linear(C, N_LET)
        # compress perpendicular features before conjoining into the score head:
        self.perp_summary = nn.Linear(C, C)
        # per-anchor categorical best-score (own-orientation feats + perp summary).
        # n_score_bins logits -> softmax PMF B_hat over scores 0..n-2 plus a
        # catch-all top bin P(score >= n-1). Range includes the +50 bingo bonus.
        self.n_score_bins = n_score_bins
        self.anchor_score_head = nn.Linear(2 * C, n_score_bins)
        # optimal-placement occupancy (union target), per square per letter:
        self.occ_head = nn.Linear(2 * C, N_LET)

    # ---- run the shared lane model on rows and on cols (transpose-shared) ----
    def _run_lanes(self, H, rack_tokens):
        """H: (B, C, S, S).  Returns row_feat, col_feat: (B, S, S, C),
        both indexed [b, row, col, :]."""
        B, C, Sz, _ = H.shape
        nt = self.n_rack_tokens

        def run(seq):                              # seq: (B*Sz, Sz, C)
            M = seq.size(0)
            tok = rack_tokens.repeat_interleave(Sz, dim=0)   # (B*Sz, nt, C)
            x = torch.cat([tok, seq], dim=1)        # (M, nt+Sz, C)
            return self.lane(x)[:, nt:, :]          # drop tokens -> (M, Sz, C)

        # rows: each row is a sequence over columns.  [b, row, col]
        rows = H.permute(0, 2, 3, 1).reshape(B * Sz, Sz, C)
        row_feat = run(rows).reshape(B, Sz, Sz, C)

        # cols: each col is a sequence over rows.    run gives [b, col, row]
        cols = H.permute(0, 3, 2, 1).reshape(B * Sz, Sz, C)
        col_feat = run(cols).reshape(B, Sz, Sz, C).permute(0, 2, 1, 3)  # -> [b,row,col]
        return row_feat, col_feat

    def forward(self, board, blank_mask, wmult, lmult, rack):
        B = board.size(0)

        # --- embed board ---
        e = torch.cat(
            [self.letter_emb(board), self.wmult_emb(wmult),
             self.lmult_emb(lmult), blank_mask.unsqueeze(-1)],
            dim=-1,
        ).permute(0, 3, 1, 2)                       # (B, in_dim, S, S)
        H = self.stem(e)                            # (B, C, S, S)

        # --- inject rack via FiLM, get rack tokens ---
        gamma, beta, rack_tokens = self.rack_enc(rack)
        H = gamma[:, :, None, None] * H + beta[:, :, None, None]

        # --- conv board encoder ---
        for blk in self.conv:
            H = blk(H)

        # --- transpose-shared lane model (the lexical store, run twice) ---
        row_feat, col_feat = self._run_lanes(H, rack_tokens)   # (B,S,S,C) each

        # --- word legality, both orientations (same head) ---
        # horiz_legal[b,r,c,l]: is letter l at (r,c) legal w.r.t. its HORIZONTAL
        # word? (from row_feat). vert_legal: vertical word (from col_feat).
        horiz_legal = self.legal_head(row_feat)     # (B,S,S,26)
        vert_legal = self.legal_head(col_feat)      # (B,S,S,26)

        # --- per-anchor score/occupancy, both orientations ---
        # Horizontal play at (r,c): main word from row_feat (own orientation);
        # cross-word legality from col_feat (perpendicular) via perp_summary.
        def heads(own, perp):
            x = torch.cat([own, self.perp_summary(perp)], dim=-1)  # (B,S,S,2C)
            return (self.anchor_score_head(x),       # PMF logits over score bins
                    self.occ_head(x))                # (B,S,S,26)

        h_score, h_occ = heads(row_feat, col_feat)
        v_score, v_occ = heads(col_feat, row_feat)

        # --- structural max-pool -> global scalar ---
        h_es = pmf_expected_score(h_score)             # (B,S,S)
        v_es = pmf_expected_score(v_score)
        anchor_es = torch.stack([h_es, v_es], dim=1)   # (B, 2, S, S)
        global_score = anchor_es.flatten(1).amax(dim=1)            # (B,)

        return {
            "global_score": global_score,            # (B,)         <- the target
            "anchor_score_logits": (h_score, v_score),  # ordinal, dense supervise
            "anchor_expected_score": anchor_es,      # (B,2,S,S)    pooling input
            "occupancy_logits": (h_occ, v_occ),      # union optimal-move target
            "horiz_legal": horiz_legal,              # cross/main legality probe
            "vert_legal": vert_legal,
        }


# ---------------------------------------------------------------------------
# Smoke test: random inputs, check shapes + that loss backprops.
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    torch.manual_seed(0)
    B = 4
    net = ScrabbleMaxScoreNet()
    board = torch.randint(0, N_TILE, (B, S, S))
    blank_mask = (torch.rand(B, S, S) < 0.02).float()
    wmult = torch.randint(0, 3, (B, S, S))
    lmult = torch.randint(0, 3, (B, S, S))
    rack = torch.randint(0, 3, (B, 27)).float()

    out = net(board, blank_mask, wmult, lmult, rack)
    for k, v in out.items():
        if isinstance(v, tuple):
            print(f"{k:24s} tuple{tuple(x.shape for x in v)}")
        else:
            print(f"{k:24s} {tuple(v.shape)}")

    n_params = sum(p.numel() for p in net.parameters())
    print(f"\nparams: {n_params/1e6:.2f}M")

    # fake multi-task loss touching EVERY head, to confirm the graph is fully
    # connected and differentiable end to end. The score head uses the two new
    # losses (PDF = cross-entropy, CDF = discrete CRPS) against random per-anchor
    # target bins; a real run supplies GADDAG-derived per-anchor best-scores
    # (clamped to [0, n_bins-1]) plus a validity mask.
    n_bins = net.n_score_bins
    tgt_bin = torch.randint(0, n_bins, (B, S, S))        # per-anchor target bins
    mask = (torch.rand(B, S, S) > 0.5)                   # pretend some anchors valid

    loss = F.mse_loss(out["global_score"], torch.rand(B) * 80)
    for logits in out["anchor_score_logits"]:            # (h_score, v_score)
        loss = loss + score_pdf_loss(logits, tgt_bin, mask)
        loss = loss + 0.1 * score_cdf_loss(logits, tgt_bin, mask)
    loss = loss + sum(t.float().mean() for t in out["occupancy_logits"])
    loss = loss + out["horiz_legal"].mean() + out["vert_legal"].mean()
    loss.backward()
    grad_ok = all(p.grad is not None for p in net.parameters() if p.requires_grad)
    print(f"loss: {loss.item():.3f}   all grads present: {grad_ok}")
