// Suite 1 hop B: confirm the TensorRT inference path (plus the C++ Eval decode)
// reproduces the PyTorch reference the dashboard runs on.
//
// The fixture is a directory holding model.onnx, inputs.bin (N x kInputFloats
// float32), and expected.bin (N x 6 float32: win_prob, p_win, p_draw, p_loss,
// score_diff_mean, score_diff_std, the PyTorch decode), produced by
// py/scripts/position_eval/gen_parity_fixture.py. This test loads the model through
// TrtEvalService and evaluates the rows at FP16 -- the precision production
// inference runs -- holding every field to a tight tolerance against the PyTorch
// FP32 reference. FP16 is the coarser precision, so its deviation bounds FP32's;
// passing it validates the engine build, host/device copies, output binding
// order, and the softmax/mean decode. Fails if any field drifts beyond tolerance.
//
// Run it as a one-liner with no arguments:
//   test_nn_inference_parity
// It generates a fresh fixture into a temp dir (by invoking the Python
// generator at the build-time SCRIBBLEZ_PY_DIR), runs the comparison, and
// cleans up. If the fixture cannot be generated (no torch/onnx) the test is
// reported as skipped. Pass an explicit directory as the first non-gtest
// argument to reuse a fixture instead:
//   test_nn_inference_parity <fixture_dir>

#include "encoding/input_encoder.h"
#include "nn/trt_eval_service.h"
#include "nn/trt_util.h"

#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <ctime>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <random>
#include <string>
#include <vector>

// The fixture is generated by a full-layout session, so its rows carry the
// full input width.
const int kFixtureInputFloats =
  scribblez::input_floats(scribblez::InputEncodingSpec{nullptr, true});

// win_prob, p_win, p_draw, p_loss, score_diff_mean, score_diff_std
constexpr int kFieldsPerRow = 6;

// FP16 is compared against the PyTorch FP32 reference at this tight tolerance:
// the tiny fixture model and the points-scale outputs leave little room for
// genuine precision drift, so a real regression (a wrong head, a decode bug)
// shows up well outside these bounds. The test prints the actual max deviations,
// so tune here if a future model legitimately needs more slack.
constexpr float kProbTol = 1e-3f;      // bounds the four probability fields
constexpr float kScoreDiffTol = 0.2f;  // bounds the score-diff mean and std (points)

// Fixture directory given on the command line (first non-gtest argument);
// empty means self-generate one.
static std::string g_fixture_dir;

static std::vector<float> read_floats(const std::string& path) {
  std::ifstream f(path, std::ios::binary | std::ios::ate);
  if (!f) {
    ADD_FAILURE() << "cannot open " << path;
    return {};
  }
  const std::streamsize bytes = f.tellg();
  f.seekg(0);
  std::vector<float> out(size_t(bytes) / sizeof(float));
  f.read(reinterpret_cast<char*>(out.data()), bytes);
  return out;
}

// Pack one row's decoded head floats into the same 6-field order as
// expected.bin: win_prob (P(win) + 0.5 * P(draw)), the three probabilities,
// then the score-diff pair.
static void pack(const float* wld, const float* sd, float* dst) {
  dst[0] = wld[0] + 0.5f * wld[1];
  dst[1] = wld[0];
  dst[2] = wld[1];
  dst[3] = wld[2];
  dst[4] = sd[0];
  dst[5] = sd[1];
}

// Evaluate every row under `precision` and check the worst per-field deviation
// from the PyTorch reference: kProbTol bounds the probability fields, and
// kScoreDiffTol the score-diff mean and std. Prints the actual max deviations
// so the tolerances can be tuned against a future model.
static void check_precision(const std::string& onnx_path, scribblez::nn::Precision precision,
                            const char* label, const std::vector<float>& inputs,
                            const std::vector<float>& expected, int n) {
  using Spec = scribblez::nn::PositionEvaluationSpec;
  scribblez::nn::NeuralNetParams<Spec> params;
  params.onnx_path = onnx_path;
  params.max_rows = n;
  params.precision = precision;
  // The parity check validates the inference stack (engine bindings, host/device
  // copies, the C++ decode), not kernel-tactic quality, so build the engine at
  // optimization level 0 to keep the cold engine build to a few seconds.
  params.fast_build = true;
  scribblez::nn::TrtEvalService<Spec> service(params);
  service.load();

  std::vector<float> wld(size_t(n) * scribblez::nn::WldOutput::kRowElems);
  std::vector<float> sd(size_t(n) * scribblez::nn::ScoreDiffOutput::kRowElems);
  float* const head_out[] = {wld.data(), sd.data()};
  service.evaluate({inputs.data(), n}, head_out);

  float max_prob_err = 0.0f;
  float max_sd_err = 0.0f;
  for (int i = 0; i < n; ++i) {
    float got[kFieldsPerRow];
    pack(wld.data() + size_t(i) * scribblez::nn::WldOutput::kRowElems,
         sd.data() + size_t(i) * scribblez::nn::ScoreDiffOutput::kRowElems, got);
    const float* exp = expected.data() + size_t(i) * kFieldsPerRow;
    for (int k = 0; k < 4; ++k) max_prob_err = std::max(max_prob_err, std::abs(got[k] - exp[k]));
    max_sd_err = std::max(max_sd_err, std::abs(got[4] - exp[4]));  // mean
    max_sd_err = std::max(max_sd_err, std::abs(got[5] - exp[5]));  // std
  }

  std::cout << "  [" << label << "] max prob err = " << max_prob_err << " (tol " << kProbTol
            << "), max score_diff_mean err = " << max_sd_err << " (tol " << kScoreDiffTol << ")\n";
  EXPECT_LE(max_prob_err, kProbTol);
  EXPECT_LE(max_sd_err, kScoreDiffTol);
}

#ifdef SCRIBBLEZ_PY_DIR
// Create a unique scratch directory for a self-generated fixture.
static std::filesystem::path make_scratch_dir() {
  std::filesystem::path base = std::filesystem::temp_directory_path() /
                               ("scribblez_nnparity_" + std::to_string(::time(nullptr)) + "_" +
                                std::to_string(std::random_device{}()));
  std::filesystem::create_directories(base);
  return base;
}

// Invoke the Python fixture generator (at build-time SCRIBBLEZ_PY_DIR) to write
// model.onnx / inputs.bin / expected.bin into `out_dir`. Returns false if the
// generator is unavailable or fails (e.g. torch/onnx not installed).
static bool generate_fixture(const std::string& out_dir) {
  const std::string py_dir = SCRIBBLEZ_PY_DIR;
  const std::string cmd = "cd \"" + py_dir + "\" && PYTHONPATH=\"" + py_dir +
                          "\" python3 -m scripts.position_eval.gen_parity_fixture --out-dir \"" +
                          out_dir + "\" --num-rows 8";
  return std::system(cmd.c_str()) == 0;
}
#endif

// Resolves the fixture directory: the one passed on the command line if any,
// else a self-generated scratch dir (removed on teardown, and skipping the
// test when the Python generator is unavailable).
class NnInferenceParityTest : public ::testing::Test {
 protected:
  void SetUp() override;
  void TearDown() override {
    if (!scratch_.empty()) std::filesystem::remove_all(scratch_);
  }

  std::string dir_;
  std::filesystem::path scratch_;  // non-empty iff this test created the fixture
};

void NnInferenceParityTest::SetUp() {
  if (!g_fixture_dir.empty()) {
    dir_ = g_fixture_dir;
    return;
  }
#ifdef SCRIBBLEZ_PY_DIR
  scratch_ = make_scratch_dir();
  dir_ = scratch_.string();
  if (!generate_fixture(dir_)) {
    GTEST_SKIP() << "could not generate fixture; is torch/onnx installed?";
  }
#else
  GTEST_SKIP() << "built without SCRIBBLEZ_PY_DIR; pass a fixture dir on the command line";
#endif
}

TEST_F(NnInferenceParityTest, Fp16MatchesPyTorchReference) {
  const std::string onnx_path = dir_ + "/model.onnx";
  std::vector<float> inputs = read_floats(dir_ + "/inputs.bin");
  std::vector<float> expected = read_floats(dir_ + "/expected.bin");

  ASSERT_EQ(inputs.size() % kFixtureInputFloats, 0u)
    << "inputs.bin size " << inputs.size() << " not a multiple of the full input width "
    << kFixtureInputFloats;
  const int n = inputs.size() / kFixtureInputFloats;
  ASSERT_GT(n, 0);
  ASSERT_EQ(expected.size(), size_t(n) * kFieldsPerRow) << "(N=" << n << ")";

  std::cout << "  " << n << " rows from " << dir_ << "\n";
  check_precision(onnx_path, scribblez::nn::Precision::kFP16, "FP16", inputs, expected, n);
}

// Custom main (instead of gtest_main): InitGoogleTest strips the gtest flags,
// and the first remaining argument, if any, names a fixture directory to reuse.
int main(int argc, char** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  if (argc >= 2) g_fixture_dir = argv[1];
  return RUN_ALL_TESTS();
}
