// MoveSetNet's TensorRT path against the PyTorch model it serves (docs/roadmap.md, A4).
//
// The move set evaluation model is fed seven input tensors across three dtypes
// and scores a whole candidate set in one pass, so more can go silently wrong
// here than in the position runtime: a mis-sized binding, a move tensor bound
// to the wrong device pointer, a chunk boundary that drops rows, or -- the
// hazard the A4 plan front-loaded a probe for -- a plan-cache hit whose refit
// maps a checkpoint's weights incorrectly and quietly serves an A/B chimera.
// Each of those changes the numbers, and every case here is a comparison
// against the PyTorch reference for the same inputs.
//
// The fixture (two same-architecture random-init models, a version-stale third,
// one board row, and one candidate set) is generated by
// py/scripts/move_set_eval/gen_mset_parity_fixture.py, invoked at the
// build-time SCRIBBLEZ_PY_DIR; the test is reported as skipped when that
// generator cannot run (no torch/onnx). Pass a fixture directory as the first
// non-gtest argument to reuse one instead:
//   test_mset_inference_parity <fixture_dir>
// The engine-plan cache always goes to a fresh scratch root, so a run builds
// its own plans and the refit case sees the plan its own first load built.

#include "nn/eval_service.h"
#include "nn/move_set_eval_service.h"
#include "nn/move_set_net.h"
#include "nn/neural_net.h"
#include "training/move_set_encoder.h"

#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <ctime>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <random>
#include <string>
#include <vector>

using scribblez::move_set::MoveFeatureArrays;
using scribblez::nn::Eval;
using scribblez::nn::Precision;

namespace {

// win_prob, p_win, p_draw, p_loss, score_diff_mean, score_diff_std
constexpr int kFieldsPerRow = 6;

// How far a run may deviate from the PyTorch reference, per field group: the
// four probabilities, and the score-diff pair, which is in points and so on its
// own scale.
struct Tolerance {
  float prob;
  float score_diff;
};

// FP32 deviates from the reference only by kernel and reduction order; FP16
// additionally by its own precision, over an attention softmax across 225 board
// tokens. Both are far tighter than any real defect: a mis-bound tensor or a
// wrong refit moves the outputs by order-one amounts, not by these. The test
// prints the actual deviations, so tune here if a future model legitimately
// needs more slack.
constexpr Tolerance kFp32Tol{1e-4f, 0.01f};
constexpr Tolerance kFp16Tol{5e-3f, 0.2f};

// Fixture directory given on the command line (first non-gtest argument);
// empty means self-generate one.
std::string g_fixture_dir;

template <typename T>
std::vector<T> read_binary(const std::string& path) {
  std::ifstream f(path, std::ios::binary | std::ios::ate);
  if (!f) {
    ADD_FAILURE() << "cannot open " << path;
    return {};
  }
  const std::streamsize bytes = f.tellg();
  f.seekg(0);
  std::vector<T> out(static_cast<size_t>(bytes) / sizeof(T));
  f.read(reinterpret_cast<char*>(out.data()), bytes);
  return out;
}

std::filesystem::path make_scratch_dir(const char* prefix) {
  std::filesystem::path base = std::filesystem::temp_directory_path() /
                               (prefix + std::to_string(::time(nullptr)) + "_" +
                                std::to_string(static_cast<unsigned long>(std::random_device{}())));
  std::filesystem::create_directories(base);
  return base;
}

// Invoke the Python fixture generator (at build-time SCRIBBLEZ_PY_DIR) to write
// the models, inputs, and expectations into `out_dir`. Returns false if the
// generator is unavailable or fails (e.g. torch/onnx not installed).
bool generate_fixture(const std::string& out_dir) {
#ifdef SCRIBBLEZ_PY_DIR
  const std::string py_dir = SCRIBBLEZ_PY_DIR;
  const std::string cmd = "cd \"" + py_dir + "\" && PYTHONPATH=\"" + py_dir +
                          "\" python3 -m scripts.move_set_eval.gen_mset_parity_fixture "
                          "--out-dir \"" +
                          out_dir + "\"";
  return std::system(cmd.c_str()) == 0;
#else
  (void)out_dir;
  return false;
#endif
}

// The fixture and its scratch engine-plan cache, resolved once per test.
class MsetInferenceParityTest : public ::testing::Test {
 protected:
  void SetUp() override;
  void TearDown() override {
    for (const std::filesystem::path& dir : {generated_, cache_root_}) {
      if (!dir.empty()) std::filesystem::remove_all(dir);
    }
  }

  std::string model(const char* name) const { return dir_ + "/" + name; }

  // Every candidate in the fixture, scored by the model at `onnx_path`, with
  // the engine bounded at `max_moves` (below the candidate count to exercise
  // the service's chunking).
  std::vector<Eval> run(const std::string& onnx_path, Precision precision, int max_moves);

  // Worst deviation of `got` from a reference decode, per field group.
  Tolerance worst_deviation(const std::vector<Eval>& got, const std::vector<float>& expected) const;

  // ...held to `tol`, printing the actual deviations under `label`.
  void expect_matches(const std::vector<Eval>& got, const std::vector<float>& expected,
                      const char* label, Tolerance tol) const;

  std::string dir_;
  std::filesystem::path generated_;   // non-empty iff this test generated the fixture
  std::filesystem::path cache_root_;  // scratch mount root: an empty plan cache

  std::vector<float> board_;
  MoveFeatureArrays moves_;
  std::vector<float> expected_a_;
  std::vector<float> expected_b_;
};

void MsetInferenceParityTest::SetUp() {
  cache_root_ = make_scratch_dir("scribblez_msetcache_");
  if (!g_fixture_dir.empty()) {
    dir_ = g_fixture_dir;
  } else {
    generated_ = make_scratch_dir("scribblez_msetparity_");
    dir_ = generated_.string();
    if (!generate_fixture(dir_)) {
      GTEST_SKIP() << "could not generate fixture; is torch/onnx installed?";
    }
  }

  board_ = read_binary<float>(dir_ + "/board.bin");
  moves_.letters = read_binary<int32_t>(dir_ + "/move_letters.bin");
  moves_.blanks = read_binary<uint8_t>(dir_ + "/move_blanks.bin");
  moves_.squares = read_binary<int32_t>(dir_ + "/move_squares.bin");
  moves_.tile_mask = read_binary<uint8_t>(dir_ + "/move_tile_mask.bin");
  moves_.scalars = read_binary<float>(dir_ + "/move_scalars.bin");
  moves_.count = static_cast<int>(moves_.scalars.size() / scribblez::move_set::kMoveScalars);
  expected_a_ = read_binary<float>(dir_ + "/expected_a.bin");
  expected_b_ = read_binary<float>(dir_ + "/expected_b.bin");

  ASSERT_GT(moves_.count, 0);
  ASSERT_EQ(expected_a_.size(), static_cast<size_t>(moves_.count) * kFieldsPerRow);
  ASSERT_EQ(expected_b_.size(), expected_a_.size());
}

std::vector<Eval> MsetInferenceParityTest::run(const std::string& onnx_path, Precision precision,
                                               int max_moves) {
  scribblez::nn::MoveSetNetParams params;
  params.onnx_path = onnx_path;
  params.precision = precision;
  params.max_moves = max_moves;
  params.mount_root = cache_root_.string();
  // The parity check validates the inference stack, not kernel-tactic quality,
  // so build at optimization level 0 to keep a cold build to a few seconds.
  params.fast_build = true;
  scribblez::nn::TrtMoveSetEvalService service(params);
  service.load();

  EXPECT_EQ(board_.size(), static_cast<size_t>(service.spatial_planes()) * 225 +
                             static_cast<size_t>(service.scalar_floats()))
    << "the fixture's board row is not the width the loaded model consumes";

  std::vector<Eval> evals(moves_.count);
  service.evaluate(board_.data(), moves_, evals.data());
  return evals;
}

Tolerance MsetInferenceParityTest::worst_deviation(const std::vector<Eval>& got,
                                                   const std::vector<float>& expected) const {
  Tolerance worst{0.0f, 0.0f};
  for (size_t i = 0; i < got.size(); ++i) {
    const float* want = expected.data() + i * kFieldsPerRow;
    const float fields[kFieldsPerRow] = {got[i].win_prob,        got[i].p_win,
                                         got[i].p_draw,          got[i].p_loss,
                                         got[i].score_diff_mean, got[i].score_diff_std};
    for (int k = 0; k < 4; ++k) worst.prob = std::max(worst.prob, std::abs(fields[k] - want[k]));
    for (int k = 4; k < kFieldsPerRow; ++k) {
      worst.score_diff = std::max(worst.score_diff, std::abs(fields[k] - want[k]));
    }
  }
  return worst;
}

void MsetInferenceParityTest::expect_matches(const std::vector<Eval>& got,
                                             const std::vector<float>& expected, const char* label,
                                             Tolerance tol) const {
  const Tolerance worst = worst_deviation(got, expected);
  std::cout << "  [" << label << "] max prob err = " << worst.prob << " (tol " << tol.prob
            << "), max score_diff err = " << worst.score_diff << " (tol " << tol.score_diff
            << ")\n";
  EXPECT_LE(worst.prob, tol.prob) << label;
  EXPECT_LE(worst.score_diff, tol.score_diff) << label;
}

TEST_F(MsetInferenceParityTest, MatchesPyTorchReferenceAtBothPrecisions) {
  expect_matches(run(model("model_a.onnx"), Precision::kFP32, moves_.count), expected_a_, "FP32",
                 kFp32Tol);
  expect_matches(run(model("model_a.onnx"), Precision::kFP16, moves_.count), expected_a_, "FP16",
                 kFp16Tol);
}

// A real move set runs to thousands of candidates, so the service splitting one
// into engine-sized chunks is the normal path, not an edge case: the last chunk
// is short, and every chunk re-sends the same board.
TEST_F(MsetInferenceParityTest, ChunksACandidateSetLargerThanTheEngine) {
  const int chunk = 8;
  ASSERT_GT(moves_.count, chunk) << "the fixture must exceed the chunk size to test chunking";
  ASSERT_NE(moves_.count % chunk, 0) << "the fixture must leave a short final chunk";

  expect_matches(run(model("model_a.onnx"), Precision::kFP32, chunk), expected_a_, "chunked",
                 kFp32Tol);
}

// The plan cache is keyed on architecture, so the second checkpoint of one
// architecture deserializes the first's plan and refits it. Nothing structural
// would notice a refit that mapped weights wrongly -- the shapes are identical
// -- so the check is that model B, loaded through A's plan, reproduces B's own
// reference and not A's.
TEST_F(MsetInferenceParityTest, RefitSwapsInTheSecondCheckpointsWeights) {
  const Tolerance from_a =
    worst_deviation(run(model("model_a.onnx"), Precision::kFP32, moves_.count), expected_a_);
  ASSERT_LE(from_a.prob, kFp32Tol.prob)
    << "model A must serve correctly before the cache is reused";

  // Loading B now hits the plan A just built.
  const std::vector<Eval> from_b = run(model("model_b.onnx"), Precision::kFP32, moves_.count);
  expect_matches(from_b, expected_b_, "refit", kFp32Tol);

  // Guard the guard: if the two random-init models happened to agree, the
  // comparison above would pass on an engine that was never refitted.
  EXPECT_GT(worst_deviation(from_b, expected_a_).prob, 100 * kFp32Tol.prob)
    << "the two fixture models are too alike to detect a missing refit";
}

// The move-feature encoding is a semantics version, not a shape: a checkpoint
// trained on older rows loads and runs without complaint, silently off
// distribution. The version guard is the only thing standing between an agent
// and that, which makes it worth a test of its own -- as is the graph guard on
// the other side, which keeps a move set model out of the position runtime.
TEST_F(MsetInferenceParityTest, RejectsAStaleEncodingVersionOrTheWrongGraph) {
  scribblez::nn::MoveSetNetParams stale;
  stale.onnx_path = model("model_stale.onnx");
  stale.mount_root = cache_root_.string();
  stale.fast_build = true;
  EXPECT_THROW(scribblez::nn::MoveSetNet(stale).load(), std::runtime_error);

  scribblez::nn::NeuralNetParams position;
  position.onnx_path = model("model_a.onnx");
  position.mount_root = cache_root_.string();
  position.fast_build = true;
  EXPECT_THROW(scribblez::nn::NeuralNet(position).load(), std::runtime_error);
}

}  // namespace

// Custom main (instead of gtest_main): InitGoogleTest strips the gtest flags,
// and the first remaining argument, if any, names a fixture directory to reuse.
int main(int argc, char** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  if (argc >= 2) g_fixture_dir = argv[1];
  return RUN_ALL_TESTS();
}
