// MoveSetNet's TensorRT path against the PyTorch model it serves (docs/roadmap.md, A4).
//
// The move set evaluation model is fed seven input tensors across three dtypes
// and scores a whole candidate set in one pass, so more can go silently wrong
// here than in the position runtime: a mis-sized binding, a move tensor bound
// to the wrong device pointer, a chunk boundary that drops rows, or -- the
// hazard the A4 plan front-loaded a probe for -- a plan-cache hit that serves
// one checkpoint's weights for another. Each of those changes the numbers, and
// every case here is a comparison against the PyTorch reference for the same
// inputs.
//
// The fixture (two same-architecture random-init models, a version-stale third,
// one board row, and one candidate set) is generated by
// py/scripts/move_set_eval/gen_mset_parity_fixture.py, invoked at the
// build-time SCRIBBLEZ_PY_DIR; the test is reported as skipped when that
// generator cannot run (no torch/onnx). Pass a fixture directory as the first
// non-gtest argument to reuse one instead:
//   test_mset_inference_parity <fixture_dir>
// ReusesAPlanPerCheckpointAndNeverMixesThem, the test that examines cache
// contents, gets its own fresh scratch root each run so it counts only the
// plans it built itself. The other cases share one persistent plan cache
// across runs of this binary (MsetInferenceParityCachedTest, below) -- safe
// because the cache is keyed on the model's exact content and the fixture
// generator's fixed seed makes model_a/model_b byte-identical every run, so
// a build from an earlier run is a valid hit rather than stale reuse.

#include "nn/eval_service.h"
#include "nn/move_set_net.h"
#include "nn/neural_net.h"
#include "nn/trt_move_set_eval_service.h"
#include "training/move_set_encoder.h"

#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <ctime>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <random>
#include <string>
#include <vector>

using scribblez::move_set::MoveFeatureArrays;
using scribblez::nn::Eval;
using scribblez::nn::Precision;

namespace {

// win_prob, p_win, p_draw, p_loss, score_diff_mean, score_diff_std
constexpr int kFieldsPerRow = 6;

// How far a run may deviate from the PyTorch reference, per field group: the
// four probabilities, and the score-diff pair, which is in points and so on its
// own scale.
struct Tolerance {
  float prob;
  float score_diff;
};

// FP32 deviates from the reference only by kernel and reduction order; FP16
// additionally by its own precision, over an attention softmax across 225 board
// tokens. Both are far tighter than any real defect: a mis-bound tensor or a
// plan-cache hit serving the wrong checkpoint moves the outputs by order-one
// amounts, not by these. The test prints the actual deviations, so tune here if
// a future model legitimately needs more slack.
//
// The FP16 tolerance is the loose one for a reason worth knowing: the flag only
// permits reduced precision, and whether TensorRT then picks FP16 kernels is
// sensitive to builder configuration that has nothing to do with precision --
// asking for a refittable plan is enough to make it choose FP32 throughout, at
// which point the FP16 run reproduces the FP32 run bit for bit. As configured
// it does pick them (the FP16 run deviates by ~6e-05), so this case tests FP16
// arithmetic; under a future constraint it would quietly narrow to covering the
// FP16 path alone rather than failing.
constexpr Tolerance kFp32Tol{1e-4f, 0.01f};
constexpr Tolerance kFp16Tol{5e-3f, 0.2f};

// Fixture directory given on the command line (first non-gtest argument);
// empty means self-generate one.
std::string g_fixture_dir;

template <typename T>
std::vector<T> read_binary(const std::string& path) {
  std::ifstream f(path, std::ios::binary | std::ios::ate);
  if (!f) {
    ADD_FAILURE() << "cannot open " << path;
    return {};
  }
  const std::streamsize bytes = f.tellg();
  f.seekg(0);
  std::vector<T> out(static_cast<size_t>(bytes) / sizeof(T));
  f.read(reinterpret_cast<char*>(out.data()), bytes);
  return out;
}

std::filesystem::path make_scratch_dir(const char* prefix) {
  std::filesystem::path base = std::filesystem::temp_directory_path() /
                               (prefix + std::to_string(::time(nullptr)) + "_" +
                                std::to_string(static_cast<unsigned long>(std::random_device{}())));
  std::filesystem::create_directories(base);
  return base;
}

// Invoke the Python fixture generator (at build-time SCRIBBLEZ_PY_DIR) to write
// the models, inputs, and expectations into `out_dir`. Returns false if the
// generator is unavailable or fails (e.g. torch/onnx not installed).
bool generate_fixture(const std::string& out_dir) {
#ifdef SCRIBBLEZ_PY_DIR
  const std::string py_dir = SCRIBBLEZ_PY_DIR;
  const std::string cmd = "cd \"" + py_dir + "\" && PYTHONPATH=\"" + py_dir +
                          "\" python3 -m scripts.move_set_eval.gen_mset_parity_fixture "
                          "--out-dir \"" +
                          out_dir + "\"";
  return std::system(cmd.c_str()) == 0;
#else
  (void)out_dir;
  return false;
#endif
}

// The message of the std::runtime_error loading `params` through `Net` must
// throw. Records a failure and returns "" if the load instead succeeds.
template <typename Net, typename Params>
std::string load_failure_message(const Params& params) {
  try {
    Net(params).load();
  } catch (const std::runtime_error& e) {
    return e.what();
  }
  ADD_FAILURE() << "loading " << params.onnx_path << " should have been rejected";
  return "";
}

// The fixture and its scratch engine-plan cache, resolved once per test.
class MsetInferenceParityTest : public ::testing::Test {
 protected:
  void SetUp() override;
  void TearDown() override {
    if (!generated_.empty()) std::filesystem::remove_all(generated_);
    if (!cache_root_.empty() && owns_cache_root()) std::filesystem::remove_all(cache_root_);
  }

  // A fresh, private plan cache by default, so a test sees only the plans it
  // built itself. Overridden by MsetInferenceParityCachedTest for the tests
  // that don't examine cache contents and would otherwise pay a full
  // TensorRT build every run for no reason.
  virtual std::filesystem::path make_cache_root() const {
    return make_scratch_dir("scribblez_msetcache_");
  }
  virtual bool owns_cache_root() const { return true; }

  std::string model(const char* name) const { return dir_ + "/" + name; }

  // Every candidate in the fixture, scored by the model at `onnx_path`, with
  // the engine bounded at `max_moves` (below the candidate count to exercise
  // the service's chunking).
  std::vector<Eval> run(const std::string& onnx_path, Precision precision, int max_moves);

  // Engine plans sitting in this test's scratch cache, in no particular order.
  std::vector<std::filesystem::path> cached_plans() const;

  // Worst deviation of `got` from a reference decode, per field group.
  Tolerance worst_deviation(const std::vector<Eval>& got, const std::vector<float>& expected) const;

  // ...held to `tol`, printing the actual deviations under `label`.
  void expect_matches(const std::vector<Eval>& got, const std::vector<float>& expected,
                      const char* label, Tolerance tol) const;

  std::string dir_;
  std::filesystem::path generated_;   // non-empty iff this test generated the fixture
  std::filesystem::path cache_root_;  // scratch mount root: an empty plan cache

  std::vector<float> board_;
  MoveFeatureArrays moves_;
  std::vector<float> expected_a_;
  std::vector<float> expected_b_;
};

void MsetInferenceParityTest::SetUp() {
  cache_root_ = make_cache_root();
  std::filesystem::create_directories(cache_root_);
  if (!g_fixture_dir.empty()) {
    dir_ = g_fixture_dir;
  } else {
    generated_ = make_scratch_dir("scribblez_msetparity_");
    dir_ = generated_.string();
    if (!generate_fixture(dir_)) {
      GTEST_SKIP() << "could not generate fixture; is torch/onnx installed?";
    }
  }

  board_ = read_binary<float>(dir_ + "/board.bin");
  moves_.letters = read_binary<int32_t>(dir_ + "/move_letters.bin");
  moves_.blanks = read_binary<uint8_t>(dir_ + "/move_blanks.bin");
  moves_.squares = read_binary<int32_t>(dir_ + "/move_squares.bin");
  moves_.tile_mask = read_binary<uint8_t>(dir_ + "/move_tile_mask.bin");
  moves_.scalars = read_binary<float>(dir_ + "/move_scalars.bin");
  moves_.count = static_cast<int>(moves_.scalars.size() / scribblez::move_set::kMoveScalars);
  expected_a_ = read_binary<float>(dir_ + "/expected_a.bin");
  expected_b_ = read_binary<float>(dir_ + "/expected_b.bin");

  ASSERT_GT(moves_.count, 0);
  ASSERT_EQ(expected_a_.size(), static_cast<size_t>(moves_.count) * kFieldsPerRow);
  ASSERT_EQ(expected_b_.size(), expected_a_.size());
}

std::vector<Eval> MsetInferenceParityTest::run(const std::string& onnx_path, Precision precision,
                                               int max_moves) {
  scribblez::nn::MoveSetNetParams params;
  params.onnx_path = onnx_path;
  params.precision = precision;
  params.max_moves = max_moves;
  params.mount_root = cache_root_.string();
  // The parity check validates the inference stack, not kernel-tactic quality,
  // so build at optimization level 0 to keep a cold build to a few seconds.
  params.fast_build = true;
  scribblez::nn::TrtMoveSetEvalService service(params);
  service.load();

  EXPECT_EQ(board_.size(), static_cast<size_t>(service.spatial_planes()) * 225 +
                             static_cast<size_t>(service.scalar_floats()))
    << "the fixture's board row is not the width the loaded model consumes";

  std::vector<Eval> evals(moves_.count);
  service.evaluate(board_.data(), moves_, evals.data());
  return evals;
}

std::vector<std::filesystem::path> MsetInferenceParityTest::cached_plans() const {
  std::vector<std::filesystem::path> plans;
  for (const auto& entry : std::filesystem::recursive_directory_iterator(cache_root_)) {
    if (entry.path().extension() == ".engine") plans.push_back(entry.path());
  }
  return plans;
}

Tolerance MsetInferenceParityTest::worst_deviation(const std::vector<Eval>& got,
                                                   const std::vector<float>& expected) const {
  Tolerance worst{0.0f, 0.0f};
  for (size_t i = 0; i < got.size(); ++i) {
    const float* want = expected.data() + i * kFieldsPerRow;
    const float fields[kFieldsPerRow] = {got[i].win_prob,        got[i].p_win,
                                         got[i].p_draw,          got[i].p_loss,
                                         got[i].score_diff_mean, got[i].score_diff_std};
    for (int k = 0; k < kFieldsPerRow; ++k) {
      // A NaN would otherwise vanish here: std::max returns its first argument
      // whenever the comparison is false, and every comparison against NaN is,
      // so a run whose rows all came back NaN -- what reading an unbound or
      // uninitialized device buffer can look like, one of the hazards this
      // suite exists to catch -- would report a perfect match.
      const float deviation = std::abs(fields[k] - want[k]);
      if (!std::isfinite(deviation)) {
        ADD_FAILURE() << "non-finite output: move " << i << " field " << k << " = " << fields[k];
        continue;
      }
      float& tracked = k < 4 ? worst.prob : worst.score_diff;
      tracked = std::max(tracked, deviation);
    }
  }
  return worst;
}

void MsetInferenceParityTest::expect_matches(const std::vector<Eval>& got,
                                             const std::vector<float>& expected, const char* label,
                                             Tolerance tol) const {
  const Tolerance worst = worst_deviation(got, expected);
  std::cout << "  [" << label << "] max prob err = " << worst.prob << " (tol " << tol.prob
            << "), max score_diff err = " << worst.score_diff << " (tol " << tol.score_diff
            << ")\n";
  EXPECT_LE(worst.prob, tol.prob) << label;
  EXPECT_LE(worst.score_diff, tol.score_diff) << label;
}

// A plan cache keyed on model content (see load()'s cache_path, above), and
// the fixture generator's fixed --seed, which makes model_a byte-identical
// every run: a plan built here survives to speed up every later run of this
// binary, this process or the next. ReusesAPlanPerCheckpointAndNeverMixesThem
// needs to see an empty cache to prove cold-build-vs-reuse, so it keeps its
// own scratch cache instead of this one.
class MsetInferenceParityCachedTest : public MsetInferenceParityTest {
 protected:
  std::filesystem::path make_cache_root() const override {
    return std::filesystem::temp_directory_path() / "scribblez_msetparity_shared_cache";
  }
  bool owns_cache_root() const override { return false; }
};

TEST_F(MsetInferenceParityCachedTest, MatchesPyTorchReferenceAtBothPrecisions) {
  expect_matches(run(model("model_a.onnx"), Precision::kFP32, moves_.count), expected_a_, "FP32",
                 kFp32Tol);
  expect_matches(run(model("model_a.onnx"), Precision::kFP16, moves_.count), expected_a_, "FP16",
                 kFp16Tol);
}

// A real move set runs to thousands of candidates, so the service splitting one
// into engine-sized chunks is the normal path, not an edge case: the last chunk
// is short, and every chunk re-sends the same board.
TEST_F(MsetInferenceParityCachedTest, ChunksACandidateSetLargerThanTheEngine) {
  const int chunk = 8;
  ASSERT_GT(moves_.count, chunk) << "the fixture must exceed the chunk size to test chunking";
  ASSERT_NE(moves_.count % chunk, 0) << "the fixture must leave a short final chunk";

  expect_matches(run(model("model_a.onnx"), Precision::kFP32, chunk), expected_a_, "chunked",
                 kFp32Tol);
}

// The plan cache must reuse a plan for the model that built it and never hand
// one checkpoint another's weights. Both halves are checked by the numbers,
// because two same-architecture checkpoints differ in nothing a shape or a
// metadata entry would catch: model A twice must build one plan and serve A's
// reference, and model B after it must serve B's own -- not A's.
TEST_F(MsetInferenceParityTest, ReusesAPlanPerCheckpointAndNeverMixesThem) {
  expect_matches(run(model("model_a.onnx"), Precision::kFP32, moves_.count), expected_a_, "A cold",
                 kFp32Tol);
  const std::vector<std::filesystem::path> after_cold = cached_plans();
  ASSERT_EQ(after_cold.size(), 1u);
  const std::filesystem::file_time_type built_at = std::filesystem::last_write_time(after_cold[0]);

  expect_matches(run(model("model_a.onnx"), Precision::kFP32, moves_.count), expected_a_,
                 "A cached", kFp32Tol);
  // A rebuild would land at the same content-keyed path and overwrite it, so
  // the file count cannot tell reuse from a silent rebuild -- the write time
  // can.
  EXPECT_EQ(std::filesystem::last_write_time(after_cold[0]), built_at)
    << "the same model must reuse its plan, not rebuild it";

  const std::vector<Eval> from_b = run(model("model_b.onnx"), Precision::kFP32, moves_.count);
  expect_matches(from_b, expected_b_, "B", kFp32Tol);
  EXPECT_EQ(cached_plans().size(), 2u) << "a different checkpoint must get its own plan";

  // Guard the guard: if the two random-init models happened to agree, the
  // comparison above would pass even on A's weights.
  EXPECT_GT(worst_deviation(from_b, expected_a_).prob, 100 * kFp32Tol.prob)
    << "the two fixture models are too alike to detect a mixed-up plan";
}

// The ways a model can be one this engine must not feed, none of which anything
// downstream would catch. A checkpoint trained on older rows has the same
// shapes and would simply run off distribution; a move set model in the
// position runtime is a different graph entirely; and a model whose move rows
// are narrower, or whose elements are smaller, builds and loads fine while the
// service stages rows at the encoder's own constants -- so feeding it would
// overrun the engine's buffers rather than fail.
TEST_F(MsetInferenceParityTest, RejectsModelsThisEncoderMustNotFeed) {
  // Each rejection is matched against what it should have objected to, so a
  // load that failed for some unrelated reason -- a fixture file that stopped
  // being written, say -- cannot pass for the guard doing its job.
  scribblez::nn::MoveSetNetParams stale;
  stale.onnx_path = model("model_stale.onnx");
  stale.mount_root = cache_root_.string();
  stale.fast_build = true;
  const std::string stale_error = load_failure_message<scribblez::nn::MoveSetNet>(stale);
  EXPECT_NE(stale_error.find("encoding version mismatch"), std::string::npos) << stale_error;

  scribblez::nn::NeuralNetParams position;
  position.onnx_path = model("model_a.onnx");
  position.mount_root = cache_root_.string();
  position.fast_build = true;
  const std::string graph_error = load_failure_message<scribblez::nn::NeuralNet>(position);
  EXPECT_NE(graph_error.find("declares graph 'move_set_eval'"), std::string::npos) << graph_error;

  scribblez::nn::MoveSetNetParams narrow;
  narrow.onnx_path = model("model_narrow.onnx");
  narrow.mount_root = cache_root_.string();
  narrow.fast_build = true;
  narrow.max_moves = moves_.count;
  const std::string width_error = load_failure_message<scribblez::nn::MoveSetNet>(narrow);
  EXPECT_NE(width_error.find("Move-feature width mismatch"), std::string::npos) << width_error;

  scribblez::nn::MoveSetNetParams small_elements = narrow;
  small_elements.onnx_path = model("model_uint8_letters.onnx");
  const std::string dtype_error = load_failure_message<scribblez::nn::MoveSetNet>(small_elements);
  EXPECT_NE(dtype_error.find("Move-feature dtype mismatch"), std::string::npos) << dtype_error;
}

}  // namespace

// Custom main (instead of gtest_main): InitGoogleTest strips the gtest flags,
// and the first remaining argument, if any, names a fixture directory to reuse.
int main(int argc, char** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  if (argc >= 2) g_fixture_dir = argv[1];
  return RUN_ALL_TESTS();
}
